import { randomUUID } from 'node:crypto';
import { requireOrganizationMembership } from '../auth/authorize.mjs';
function forbidden(code='FORBIDDEN'){throw Object.assign(new Error(code),{status:403,code});}
function requireUser(context){const id=context?.user?.id ?? (context?.subject?.type==='USER'?context.subject.id:null);if(!id) forbidden('AUTH_SUBJECT_REQUIRED');return id;}
export function subjectForContext(context,organizationId=null){
  const userId=requireUser(context);
  if(organizationId){requireOrganizationMembership(context,organizationId,{admin:true});return {type:'ORGANIZATION',id:organizationId};}
  return {type:'USER',id:userId};
}
export function createCustomerLibraryService({customerRepository,catalogRepository,downloadService,updateResolver=null,idFactory=randomUUID}={}){return {
 async getMe(context){const userId=requireUser(context);return {user:customerRepository.getUser?await customerRepository.getUser(userId):context.user??null,roles:context.roles??[],memberships:customerRepository.listMemberships?await customerRepository.listMemberships(userId):context.memberships??[]};},
 async listLibrary(context,{organizationId=null}={}){const subject=subjectForContext(context,organizationId);const entitlements=await customerRepository.listEntitlements(subject);return Promise.all(entitlements.map(async(entitlement)=>({entitlement,product:catalogRepository?.getProduct?await catalogRepository.getProduct(entitlement.product_id):null})));},
 async listUpdates(context,{organizationId=null}={}){const subject=subjectForContext(context,organizationId);const installs=customerRepository.listInstallations?await customerRepository.listInstallations(subject):[];if(!updateResolver)return installs;return Promise.all(installs.map((installation)=>updateResolver({subject,installation})));},
 async createInstallation(context,input){const subject=subjectForContext(context,input.organization_id??null);if(!input.product_version_id||!input.runtime)throw Object.assign(new Error('INVALID_INSTALLATION'),{status:400,code:'INVALID_INSTALLATION'});const version=await catalogRepository.getProductVersion(input.product_version_id);if(!version)forbidden('PRODUCT_VERSION_FORBIDDEN');const entitlements=await customerRepository.listEntitlements(subject);if(!entitlements.some((item)=>item.product_id===version.product_id&&item.status==='ACTIVE'))forbidden('ENTITLEMENT_REQUIRED');return customerRepository.upsertInstallation({id:`INS-${idFactory()}`,subject,product_version_id:version.id,runtime_distribution_id:input.runtime_distribution_id??null,runtime:String(input.runtime).toUpperCase(),installed_version:version.version,status:'INSTALLED'});},
 async createCollection(context,input){const subject=subjectForContext(context,input.organization_id??null);if(!input.name?.trim())throw Object.assign(new Error('INVALID_COLLECTION'),{status:400,code:'INVALID_COLLECTION'});return customerRepository.createCollection({id:`COL-${idFactory()}`,subject,name:input.name.trim(),visibility:subject.type==='ORGANIZATION'?'ORGANIZATION':'PRIVATE'});},
 async addCollectionItem(context,collectionId,input){const collection=await customerRepository.getCollection(collectionId);if(!collection)forbidden('COLLECTION_NOT_FOUND');const owner=collection.organization_id?{type:'ORGANIZATION',id:collection.organization_id}:{type:'USER',id:collection.user_id};if(owner.type==='ORGANIZATION')subjectForContext(context,owner.id);else if(owner.id!==requireUser(context))forbidden();return customerRepository.addCollectionItem({id:`CI-${idFactory()}`,collection_id:collectionId,product_id:input.product_id,pinned_version:input.pinned_version??null});},
 async download(context,productVersionId,runtime){if(!downloadService)throw new Error('DOWNLOAD_SERVICE_UNAVAILABLE');return downloadService.authorizeDownload(context,productVersionId,runtime);},
};}
