import { randomUUID } from 'node:crypto';
import { requireOrganizationMembership } from '../auth/authorize.mjs';
function forbidden(){throw Object.assign(new Error('FORBIDDEN'),{status:403,code:'FORBIDDEN'});}
export function subjectForContext(context,organizationId=null){if(!context?.user?.id&&context?.subject?.type!=='USER') forbidden();if(organizationId){requireOrganizationMembership(context,organizationId);return {type:'ORGANIZATION',id:organizationId};}return context.subject??{type:'USER',id:context.user.id};}
export function createCustomerLibraryService({customerRepository,catalogRepository,downloadService,updateResolver=null}={}){return {
 async getMe(context){return {user:context.user??null,roles:context.roles??[],memberships:context.memberships??[]};},
 async listLibrary(context,{organizationId=null}={}){const subject=subjectForContext(context,organizationId);const entitlements=await customerRepository.listEntitlements(subject);return Promise.all(entitlements.map(async(entitlement)=>({entitlement,product:catalogRepository.getProduct?await catalogRepository.getProduct(entitlement.product_id):null})));},
 async listUpdates(context,{organizationId=null}={}){const subject=subjectForContext(context,organizationId);const installs=customerRepository.listInstallations?await customerRepository.listInstallations(subject):[];if(!updateResolver) return installs;return Promise.all(installs.map((installation)=>updateResolver({subject,installation})));},
 async createInstallation(context,input){const subject=subjectForContext(context,input.organization_id??null);if(!input.product_version_id||!input.runtime) throw Object.assign(new Error('INVALID_INSTALLATION'),{status:400,code:'INVALID_INSTALLATION'});const version=await catalogRepository.getProductVersion(input.product_version_id);if(!version) forbidden();const entitlements=await customerRepository.listEntitlements(subject);if(!entitlements.some((item)=>item.product_id===version.product_id&&item.status==='ACTIVE')) forbidden();return customerRepository.upsertInstallation({id:input.id??`INS-${randomUUID()}`,subject,product_version_id:version.id,runtime_distribution_id:input.runtime_distribution_id??null,runtime:input.runtime,installed_version:version.version,status:'INSTALLED'});},
 async createCollection(context,input){const subject=subjectForContext(context,input.organization_id??null);if(!input.name?.trim()) throw Object.assign(new Error('INVALID_COLLECTION'),{status:400,code:'INVALID_COLLECTION'});return customerRepository.createCollection({id:input.id??`COL-${randomUUID()}`,subject,name:input.name.trim(),visibility:subject.type==='ORGANIZATION'?'ORGANIZATION':'PRIVATE'});},
 async addCollectionItem(context,collectionId,input){const collection=await customerRepository.getCollection(collectionId);if(!collection) forbidden();const subject=subjectForContext(context,collection.organization_id??null);if(subject.type==='USER'&&collection.user_id!==subject.id) forbidden();return customerRepository.addCollectionItem({id:input.id??`CI-${randomUUID()}`,collection_id:collectionId,product_id:input.product_id,pinned_version:input.pinned_version??null});},
 async download(context,productVersionId,runtime){return downloadService.authorizeDownload(context,productVersionId,runtime);},
};}
