import test from 'node:test';
import assert from 'node:assert/strict';
import { resolveEntitlement } from '../../../marketplace/customer/entitlements.mjs';
const now=new Date('2026-08-19T12:00:00Z');
function entitlement(overrides={}){return {id:'ENT-1',status:'ACTIVE',product_id:'PRD-1',version_policy:'MAJOR_PINNED',acquired_version:'1.4.0',expires_at:null,starts_at:'2026-01-01T00:00:00Z',allowed_runtimes:['UNIVERSAL','CHATGPT'],user_id:'USR-A',organization_id:null,...overrides};}
const product={id:'PRD-1'};
test('major-pinned perpetual entitlement allows newer minor/patch in same major',()=>{const result=resolveEntitlement({entitlements:[entitlement()],product,version:{version:'1.4.2'},runtime:'UNIVERSAL',now,subject:{type:'USER',id:'USR-A'}});assert.equal(result.allowed,true);assert.equal(result.entitlement_id,'ENT-1');});
test('major-pinned entitlement rejects next major',()=>assert.equal(resolveEntitlement({entitlements:[entitlement()],product,version:{version:'2.0.0'},runtime:'UNIVERSAL',now,subject:{type:'USER',id:'USR-A'}}).allowed,false));
test('expired and suspended entitlements are denied',()=>{assert.equal(resolveEntitlement({entitlements:[entitlement({expires_at:'2026-08-18T00:00:00Z'})],product,version:{version:'1.4.2'},runtime:'UNIVERSAL',now,subject:{type:'USER',id:'USR-A'}}).allowed,false);assert.equal(resolveEntitlement({entitlements:[entitlement({status:'SUSPENDED'})],product,version:{version:'1.4.2'},runtime:'UNIVERSAL',now,subject:{type:'USER',id:'USR-A'}}).allowed,false);});
test('wrong subject and runtime are denied',()=>{assert.equal(resolveEntitlement({entitlements:[entitlement()],product,version:{version:'1.4.2'},runtime:'UNIVERSAL',now,subject:{type:'USER',id:'USR-B'}}).allowed,false);assert.equal(resolveEntitlement({entitlements:[entitlement()],product,version:{version:'1.4.2'},runtime:'GEMINI',now,subject:{type:'USER',id:'USR-A'}}).allowed,false);});
test('version policies have distinct deterministic bounds',()=>{const check=(policy,acquired,target)=>resolveEntitlement({entitlements:[entitlement({version_policy:policy,acquired_version:acquired})],product,version:{version:target},runtime:'UNIVERSAL',now,subject:{type:'USER',id:'USR-A'}}).allowed;assert.equal(check('EXACT','1.4.0','1.4.0'),true);assert.equal(check('EXACT','1.4.0','1.4.1'),false);assert.equal(check('PATCH_PINNED','1.4.0','1.4.1'),false);assert.equal(check('MINOR_PINNED','1.4.0','1.4.9'),true);assert.equal(check('MINOR_PINNED','1.4.0','1.5.0'),false);assert.equal(check('MAJOR_PINNED','1.4.0','1.9.0'),true);assert.equal(check('CURRENT_WHILE_ACTIVE','1.4.0','8.0.0'),true);});
test('malformed semantic versions fail closed',()=>assert.throws(()=>resolveEntitlement({entitlements:[entitlement()],product,version:{version:'latest'},runtime:'UNIVERSAL',now,subject:{type:'USER',id:'USR-A'}}),/SEMVER/));
