import test from'node:test';import assert from'node:assert/strict';import{createRouter}from'../../../apps/marketplace-api/src/router.mjs';

test('stripe webhook is verified before authentication and preserves raw body',async()=>{let seen;const router=createRouter({services:{paymentEvents:{handle:async x=>(seen=x,{status:'RECORDED'})}}});const body='{"id":"evt_1", "exact": true}';const r=await router(new Request('http://local/v1/payments/stripe/webhook',{method:'POST',headers:{'stripe-signature':'sig'},body}));assert.equal(r.status,200);assert.equal(seen.rawBody,body);assert.equal(seen.signature,'sig');});

test('invalid payment signature maps to 400',async()=>{const router=createRouter({services:{paymentEvents:{handle:async()=>{throw Object.assign(new Error('bad'),{status:400,code:'INVALID_PAYMENT_SIGNATURE'})}}}});const r=await router(new Request('http://local/v1/payments/stripe/webhook',{method:'POST',body:'{}'}));assert.equal(r.status,400);assert.equal((await r.json()).error.code,'INVALID_PAYMENT_SIGNATURE');});

test('checkout and readiness require authenticated context',async()=>{const router=createRouter({services:{}});for(const [path,method] of [['/v1/checkout','POST'],['/v1/admin/readiness','GET']]){const r=await router(new Request(`http://local${path}`,{method,headers:method==='POST'?{'content-type':'application/json'}:{},body:method==='POST'?'{}':undefined}));assert.equal(r.status,401);}});

test('authenticated checkout and admin readiness delegate to bounded services',async()=>{const services={auth:{authenticate:async()=>({user:{id:'U'},roles:['MARKETPLACE_ADMIN'],subject:{type:'USER',id:'U'}})},checkout:{create:async(_ctx,input)=>({session:input.offerId})},readiness:{get:async()=>({DB:'PASS'})}};const router=createRouter({services});let r=await router(new Request('http://local/v1/checkout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({offerId:'OFF-1'})}));assert.equal(r.status,201);assert.equal((await r.json()).session,'OFF-1');r=await router(new Request('http://local/v1/admin/readiness'));assert.deepEqual(await r.json(),{DB:'PASS'});});
