export const PRODUCT_TYPES = Object.freeze(['SKILL', 'AGENT', 'WORKFLOW_PACK', 'COLLECTION']);
export const COMMERCIAL_STATES = Object.freeze([
  'DRAFT', 'REFERENCE_ONLY', 'FREE', 'PAID', 'PILOT', 'COMING_SOON', 'ENTERPRISE_ONLY', 'SUSPENDED', 'RETIRED',
]);
export const VERSION_STATES = Object.freeze([
  'DRAFT', 'VALIDATING', 'EVALUATING', 'COMMERCIAL_READY', 'PUBLICATION_REVIEW', 'PUBLISHED', 'SUPERSEDED', 'RETIRED',
  'BLOCKED_SCHEMA', 'BLOCKED_DEPENDENCY', 'BLOCKED_EVALUATION', 'BLOCKED_RIGHTS', 'BLOCKED_POLICY', 'BLOCKED_RUNTIME',
  'SUSPENDED', 'SECURITY_BLOCKED',
]);
export const COMPATIBILITY_STATES = Object.freeze(['VERIFIED', 'EXPERIMENTAL', 'UNAVAILABLE', 'BLOCKED', 'DEPRECATED']);
export const VISIBILITY_STATES = Object.freeze(['PRIVATE', 'UNLISTED', 'PUBLIC']);
export const AVAILABILITY_STATES = Object.freeze(['ACTIVE', 'DELISTED', 'SUSPENDED', 'SECURITY_BLOCKED', 'LEGAL_HOLD', 'RETIRED']);
