import {createHash} from 'node:crypto';
import {buildRuntimePackagePlan} from '../distribution/package-builder.mjs';

const RUNTIMES=Object.freeze(['UNIVERSAL','CHATGPT','CURSOR','GEMINI','GROK','MANUS','MCP']);
const runtimeStates=()=>Object.freeze({UNIVERSAL:'VERIFIED',CHATGPT:'EXPERIMENTAL',CURSOR:'EXPERIMENTAL',GEMINI:'EXPERIMENTAL',GROK:'EXPERIMENTAL',MANUS:'EXPERIMENTAL',MCP:'EXPERIMENTAL'});
function hash(value){return createHash('sha256').update(JSON.stringify(value)).digest('hex');}
function item(input){
  const snapshot=Object.freeze({canonical_ref:input.canonical_ref,name:input.name,type:input.type,purpose:input.purpose,boundaries:input.boundaries,fixture:input.fixture,default_integration_tier:'I0'});
  const canonical_hash=hash(snapshot);
  return Object.freeze({...input,version:'1.0.0',risk_tier:input.risk_tier??'MODERATE',default_integration_tier:'I0',offer_class:'FREE',license_class:'FREE_COMMERCIAL',runtimes:RUNTIMES,runtime_states:runtimeStates(),canonical_snapshot:snapshot,canonical_hash,product_version_id:`PV-${input.canonical_ref}-1.0.0`,provenance_receipt_id:`EVID-FIRST10-${input.canonical_ref}`,selection_scores:Object.freeze(input.selection_scores)});
}

export const FIRST_COHORT=Object.freeze([
  item({canonical_ref:'SKL-001',product_id:'PRD-0BD1D7BD75AE',type:'SKILL',name:'Structured Intake Normalization',risk_tier:'LOW',purpose:'Convert forms, briefs, tickets, and unstructured requests into a validated schema and flag missing mandatory data.',boundaries:['supplied inputs only','no external action','abstain when mandatory fields cannot be resolved'],fixture:'Incomplete or ambiguous intake with expected missing-field and escalation outputs.',selection_scores:[5,5,5,5,5,4]}),
  item({canonical_ref:'SKL-002',product_id:'PRD-9C610FB56A35',type:'SKILL',name:'Task Decomposition & Dependency Mapping',risk_tier:'LOW',purpose:'Break approved work into bounded tasks, dependencies, owners, gates, and deadlines.',boundaries:['supplied inputs only','no authority reassignment','surface dependency conflicts'],fixture:'Multi-step request with a deliberate dependency conflict.',selection_scores:[5,5,5,5,5,5]}),
  item({canonical_ref:'SKL-006',product_id:'PRD-6AAA54796EE8',type:'SKILL',name:'Claim Extraction & Source Citation',purpose:'Extract material factual claims and attach traceable sources, dates, context, and uncertainty.',boundaries:['do not invent sources','distinguish unsupported claims','no external action'],fixture:'Mixed-quality source bundle containing unsupported claims.',selection_scores:[5,4,5,5,5,5]}),
  item({canonical_ref:'SKL-013',product_id:'PRD-FD77896E6D35',type:'SKILL',name:'Requirements & Acceptance-Criteria Authoring',risk_tier:'LOW',purpose:'Convert approved outcomes into testable observable requirements, constraints, and acceptance conditions.',boundaries:['do not invent business authority','label assumptions','no production action'],fixture:'Vague requirement that must become measurable criteria.',selection_scores:[5,5,5,5,5,5]}),
  item({canonical_ref:'SKL-045',product_id:'PRD-DD6120B7A77F',type:'SKILL',name:'Evaluation Scorecard & Gate Execution',purpose:'Apply rubric-based quality, policy, technical, and completeness checks to produce reproducible pass/fail evidence.',boundaries:['cannot waive failed critical gates','no self-approval','preserve evidence'],fixture:'Artifact that passes quality but fails provenance or approval evidence.',selection_scores:[5,5,5,5,5,5]}),
  item({canonical_ref:'GKE-06',product_id:'PRD-5E93EAE77D70',type:'AGENT',name:'Research & Source Verification Agent',purpose:'Retrieve relevant supplied source material, assess provenance and currency, separate facts from assumptions, and create a cited research packet.',boundaries:['I0 supplied-input deployment','every material claim needs source/date/uncertainty','no external outreach'],fixture:'Conflicting supplied sources with stale or non-authoritative records.',selection_scores:[5,4,5,5,5,5]}),
  item({canonical_ref:'PXD-02',product_id:'PRD-C1E96EEF68D5',type:'AGENT',name:'Product Requirements Agent',purpose:'Convert approved direction into testable requirements, user stories, acceptance criteria, dependencies, and nonfunctional constraints.',boundaries:['I0 supplied-input deployment','no scope approval authority','criteria must be testable'],fixture:'Feature brief containing ambiguity and conflicting constraints.',selection_scores:[5,5,5,5,5,5]}),
  item({canonical_ref:'ESP-03',product_id:'PRD-42223C44417C',type:'AGENT',name:'Code Review & Quality Agent',purpose:'Review supplied change sets for correctness, readability, maintainability, tests, dependencies, and policy violations.',boundaries:['I0 supplied-diff deployment','human reviewer retains merge authority','no repository write or production deploy'],fixture:'Diff with passing tests but an authorization flaw.',selection_scores:[5,5,5,5,5,5]}),
  item({canonical_ref:'ESP-09',product_id:'PRD-3EFB52084A21',type:'AGENT',name:'Technical Documentation Agent',risk_tier:'LOW',purpose:'Produce and maintain implementation guides, API references, runbooks, ADR summaries, and troubleshooting documents from approved supplied technical sources.',boundaries:['I0 supplied-input deployment','tested commands and authoritative references only','no production execution'],fixture:'Technical source packet containing an obsolete command and a missing authoritative reference.',selection_scores:[5,5,5,5,5,4]}),
  item({canonical_ref:'RCP-04',product_id:'PRD-FF1A25B60A9F',type:'AGENT',name:'Proposal & RFP Response Agent',purpose:'Draft response sections, compliance matrices, evidence requests, and reusable content from approved supplied materials.',boundaries:['I0 supplied-input deployment','no submission or external send','legal/commercial/security approvals remain human'],fixture:'RFP containing an unsupported requirement claim and missing evidence.',selection_scores:[5,4,5,5,5,5]}),
]);

export function buildCohortPackagePlans(){
  return FIRST_COHORT.flatMap(product=>product.runtimes.map(runtime=>buildRuntimePackagePlan({runtime,manifest:{product_id:product.product_id,product_version_id:product.product_version_id,canonical_refs:[product.canonical_ref],canonical_hashes:[product.canonical_hash],components:[{type:product.type,canonical_ref:product.canonical_ref}],license_ref:'LIC-FIRST10-FREE-COMMERCIAL',provenance_receipt_id:product.provenance_receipt_id,runtime_adapters:product.runtimes},canonical_permissions:[],runtime_permissions:[]})));
}
